management:
  endpoints:
    web:
      exposure:
        include: beans
spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:h2:mem:testdb
    username: zacky
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 60000
      connection-timeout: 3000
      max-lifetime: 18000000
