spring:
  output:
    ansi:
      enabled: always

foo:
  datasource:
    url: jdbc:h2:mem:foo
    username: foo
    password:

bar:
  datasource:
    url: jdbc:h2:mem:bar
    username: bar
    password:
